version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"
  jobs:
    create_environment:
      - mamba env create -p .env/ --file environment-files/readthedocs.yml
    build:
      html:
        - PATH=$(pwd)/.env/bin/:$PATH q2doc refresh-cache
        - PATH=$(pwd)/.env/bin/:$PATH make autodoc
        - PATH=$(pwd)/.env/bin/:$PATH make html
        - mkdir -p $READTHEDOCS_OUTPUT
        - cp -a docs/_build/* $READTHEDOCS_OUTPUT/

conda:
  environment: environment-files/readthedocs.yml

formats:
  - pdf
