version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - "jupyter-book config sphinx moshpit_docs/ && cat moshpit_docs/conf.py"

python:
  install:
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: moshpit_docs/conf.py

formats:
  - pdf
