channels:
- https://packages.qiime2.org/qiime2/2025.7/moshpit/released
- conda-forge
- bioconda
dependencies:
  - qiime2-moshpit
  - nodejs
  - pip
  - pip:
    - q2doc@git+https://github.com/qiime2/q2doc@dev
    - jupyter-book>=2.0.0a1
