name: deploy-book

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: conda-env

    - name: Install dependencies
      run: mamba install -n conda-env jupyter-book

    - name: Build the book
      run: mamba run -n conda-env jupyter-book build moshpit_docs

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: moshpit_docs/_build/html
        publish_branch: book
        enable_jekyll: false
